<a href="https://colab.research.google.com/github/vcdemy/20240829/blob/main/20240830%E7%AD%86%E8%A8%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20240830筆記

## 複習基本資料型態及容器型別

* int, float, bool, str
* list, tuple, dict, set

### 字串的加法及乘法

In [ ]:
'abc' + '123'

'abc123'

In [ ]:
'abc' * 3

'abcabcabc'

In [ ]:
'abc' + 123

TypeError: can only concatenate str (not "int") to str

In [ ]:
'abc' + str(123)

'abc123'

In [ ]:
'abc' * 3.0

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
'abc' * int(3.0)

'abcabcabc'

### 綜合練習 01

請用 for 迴圈畫出底下金字塔。

```
      *
     ***
    *****
   *******
  *********
```

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
for i in range(5):
    print(2*i+1)

1
3
5
7
9


In [ ]:
for i in range(5):
    print('*'*(2*i+1))

*
***
*****
*******
*********


In [ ]:
for i in range(5):
    print(' '*i+'*'*(2*i+1))

*
 ***
  *****
   *******
    *********


In [ ]:
for i in range(5):
    print(' '*(5-i)+'*'*(2*i+1))

     *
    ***
   *****
  *******
 *********


### 綜合練習 02

請將上面的程式碼打包成一個函式，輸入一個整數n，畫出高度為n的金字塔。

In [ ]:
def pyramid(n):
  pass

In [ ]:
def pyramid(n):
    for i in range(n):
        print(' '*(n-i)+'*'*(2*i+1))

In [ ]:
pyramid(7)

       *
      ***
     *****
    *******
   *********
  ***********
 *************


## zerojudge.tw使用簡介

* 如何讀取資料？ => input()
* 如何印出結果？ => print()

In [ ]:
input?

In [ ]:
x = input('請輸入一個整數：')

請輸入一個整數：10


In [ ]:
x

'10'

In [ ]:
int(x)

10

In [ ]:
x + 1

TypeError: can only concatenate str (not "int") to str

In [ ]:
print?

In [ ]:
print(1, 2, 3, 4, 5)

1 2 3 4 5


In [ ]:
print(1, 2, 3, 4, 5, sep='-')

1-2-3-4-5


In [ ]:
print(1, 2, 3)
print(4, 5, 6)

1 2 3
4 5 6


In [ ]:
print(1, 2, 3, end=" ")
print(4, 5, 6)

1 2 3 4 5 6


In [ ]:
print(1, 2, 3, end="+++")
print(4, 5, 6)

1 2 3+++4 5 6


## 字串的格式化

* python2
* python3
* f-string

In [ ]:
# python2字串格式化方式
m = 1
n = 3.14159
print('m=%d, n=%f' % (m, n))

m=1, n=3.141590


In [ ]:
# python3字串格式化方式
print('m={}, n={}'.format(m, n))

m=1, n=3.14159


In [ ]:
# f-string
print(f'm={m}, n={n}')

m=1, n=3.14159


## Python的基礎語法

* 條件式 => if statements
* 迴圈 => loops
* 函式 => functions
* 例外處理 => exception handling

### 條件式

In [ ]:
m = 3
n = 2

m is greater than n


In [ ]:
if m > n:
    print('m is greater than n')

In [ ]:
if m > n:
    print('m is greater than n')
else:
    print('m is not greater than n')

m is greater than n


In [ ]:
if m > n:
    print('m is greater than n')
elif m < n:
    print('m is less than n')
else:
    print('m is equal to n')

m is greater than n


### 迴圈 (loops)

* for
* while

#### for loop

In [ ]:
for i in range(3):
    print(i)

0
1
2


In [ ]:
for i in range(3):
    print('程式區塊開始')
    print(i)
    print('程式區塊結束')

程式區塊開始
0
程式區塊結束
程式區塊開始
1
程式區塊結束
程式區塊開始
2
程式區塊結束


In [ ]:
for i in range(3):
    print('程式區塊開始')
    print(i)
print('程式區塊結束')

程式區塊開始
0
程式區塊開始
1
程式區塊開始
2
程式區塊結束


In [ ]:
x = ['aaa', 'bbb', 'ccc']

In [ ]:
for i in x:
    print(i)

aaa
bbb
ccc


In [ ]:
d = {}
d['a'] = 1
d['b'] = 2
d['c'] = 3

In [ ]:
d

{'a': 1, 'b': 2, 'c': 3}

In [ ]:
for i in d:
  print(i)

a
b
c


In [ ]:
# a => 1
# b => 2
# c => 3
for i in d:
  print(i, "==>", d[i])

a ==> 1
b ==> 2
c ==> 3


In [ ]:
# 寫一個迴圈印出彩虹的顏色
colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet']
for i in colors:
  print(i)

red
orange
yellow
green
blue
indigo
violet


In [ ]:
'a' in d

True

In [ ]:
if 'a' in d:
  print(f'a is in d, its value is {d["a"]}')

a is in d, its value is 1


#### 關於字串的引號(' v.s. ")

In [ ]:
s1 = 'my dog'

In [ ]:
s2 = "my dog"

In [ ]:
s3 = "my dog's name is Bob"

In [ ]:
s4 = 'my dog\'s name is Bob'

#### while loop

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
i = 0
while i < 5:
  print(i)
  i = i + 1  # i += 1

0
1
2
3
4


In [ ]:
# 無限迴圈
while True:
  print('Hello World!')

Streaming output truncated to the last 5000 lines.
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!


KeyboardInterrupt: 

In [ ]:
c = 0
while True:
  print('Hello World!')
  c += 1
  if c >= 5:
    break

Hello World!
Hello World!
Hello World!
Hello World!
Hello World!


In [ ]:
i = 0
while i < 5:
  if i == 2:
    i += 1
    continue
  print(i)
  i = i + 1  # i += 1

0
1
3
4


In [ ]:
for i in range(5):
  if i == 2:
    continue
  print(i)

0
1
3
4


### 函式

In [ ]:
def square01(x):
  print(x**2)

def square02(x):
  return x**2

In [ ]:
square01(2)

4


In [ ]:
square02(2)

4

In [ ]:
x1 = square01(2)

4


In [ ]:
x2 = square02(2)

In [ ]:
x1

In [ ]:
x2

4

### 例外處理(Exception Handling)

```python
try:
  程式區塊01
except Exception as e:
  程式區塊02
```

In [ ]:
def add(a, b):
  print(f"{a} + {b} = {a+b}")

def sub(a, b):
  print(f"{a} - {b} = {a-b}")

def mul(a, b):
  print(f"{a} x {b} = {a*b}")

def div(a, b):
  print(f"{a} / {b} = {a/b}")

In [ ]:
fns = [add, sub, div, mul]

In [ ]:
for i in fns:
  i(4, 2)

4 + 2 = 6
4 - 2 = 2
4 / 2 = 2.0
4 x 2 = 8


In [ ]:
for i in fns:
  i(4, 0)

4 + 0 = 4
4 - 0 = 4


ZeroDivisionError: division by zero

In [ ]:
for i in fns:
  try:
    i(4, 0)
  except Exception as e:
    print(e)

4 + 0 = 4
4 - 0 = 4
division by zero
4 x 0 = 0


### 綜合練習 03

使用例外處理，修正萌典api的應用可能產生的錯誤。

In [ ]:
import requests

def lookup(word):
  url = "https://www.moedict.tw/uni/"
  data = requests.get(url + word).json()
  try:
    return data['heteronyms'][0]['definitions'][0]['def']
  except Exception as e:
    return "發生錯誤！大概是查不到這個字吧！"

In [ ]:
lookup('教室')

'學校裡進行教學活動的房間。'

In [ ]:
lookup('apple')

'發生錯誤！大概是查不到這個字吧！'

## 網路爬蟲簡介

https://github.com/vcdemy/crawler

https://vcdemy.github.io/web

* requests ==> 抓資料
* BeautifulSoup ==> 剖析資料

### 抓取網頁原始碼

In [ ]:
import requests

In [ ]:
url = "https://vcdemy.github.io/web/html_only.html"

In [ ]:
r = requests.get(url)

In [ ]:
print(r.text)

<!DOCTYPE html>
<html>
<head>
    <title>HTML範例</title>
</head>
<body>

<h1>哈囉！HTML！</h1>

<img src="ninja.jpg" />

</body>
</html>


In [ ]:
r.status_code

200

In [ ]:
r.headers

{'Connection': 'keep-alive', 'Content-Length': '143', 'Server': 'GitHub.com', 'Content-Type': 'text/html; charset=utf-8', 'permissions-policy': 'interest-cohort=()', 'Last-Modified': 'Tue, 07 Feb 2023 13:26:17 GMT', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31556952', 'ETag': '"63e25179-8f"', 'expires': 'Fri, 30 Aug 2024 03:34:36 GMT', 'Cache-Control': 'max-age=600', 'x-proxy-cache': 'MISS', 'X-GitHub-Request-Id': 'B4F8:24E165:220F69:25A2D2:66D13B74', 'Accept-Ranges': 'bytes', 'Age': '0', 'Date': 'Fri, 30 Aug 2024 03:24:36 GMT', 'Via': '1.1 varnish', 'X-Served-By': 'cache-pdk-kfty2130044-PDK', 'X-Cache': 'MISS', 'X-Cache-Hits': '0', 'X-Timer': 'S1724988276.322351,VS0,VE21', 'Vary': 'Accept-Encoding', 'X-Fastly-Request-ID': '6efed6622d8e82d61c154b2ef779c90084d387b0'}

### 剖析網頁原始碼

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(r.text)

In [ ]:
soup.title

<title>HTML範例</title>

In [ ]:
soup.title.text

'HTML範例'

In [ ]:
print(soup.title.text)

HTML範例


In [ ]:
soup.h1

<h1>哈囉！HTML！</h1>

### 抓取圖片

In [ ]:
url = "https://vcdemy.github.io/web/ninja.jpg"

In [ ]:
r = requests.get(url)

In [ ]:
f = open('ninja.jpg', 'wb')
f.write(r.content)
f.close()

In [ ]:
with open('ninja2.jpg', 'wb') as f:
  f.write(r.content)

### 抓取 pdf 檔

In [ ]:
url = "https://arxiv.org/pdf/2408.16756"

In [ ]:
r = requests.get(url)

In [ ]:
with open('llm01.pdf', 'wb') as f:
  f.write(r.content)

### 剖析網頁，取得所有pdf檔的網址

https://www.w3schools.com/cssref/css_selectors.php

In [ ]:
url = "https://arxiv.org/search/?query=LLM&searchtype=all&source=header"

In [ ]:
r = requests.get(url)

In [ ]:
soup = BeautifulSoup(r.text)

In [ ]:
soup.title

<title>Search | arXiv e-print repository</title>

In [ ]:
soup.select("li.arxiv-result div span a")[0]

<a href="https://arxiv.org/pdf/2408.16756">pdf</a>

In [ ]:
soup.select("li.arxiv-result div span a")

[<a href="https://arxiv.org/pdf/2408.16756">pdf</a>,
 <a href="https://arxiv.org/format/2408.16756">other</a>,
 <a href="https://arxiv.org/pdf/2408.16740">pdf</a>,
 <a href="https://arxiv.org/ps/2408.16740">ps</a>,
 <a href="https://arxiv.org/format/2408.16740">other</a>,
 <a href="https://arxiv.org/pdf/2408.16737">pdf</a>,
 <a href="https://arxiv.org/format/2408.16737">other</a>,
 <a href="https://arxiv.org/pdf/2408.16730">pdf</a>,
 <a href="https://arxiv.org/format/2408.16730">other</a>,
 <a href="https://arxiv.org/pdf/2408.16700">pdf</a>,
 <a href="https://arxiv.org/format/2408.16700">other</a>,
 <a href="https://arxiv.org/pdf/2408.16673">pdf</a>,
 <a href="https://arxiv.org/format/2408.16673">other</a>,
 <a href="https://arxiv.org/pdf/2408.16667">pdf</a>,
 <a href="https://arxiv.org/format/2408.16667">other</a>,
 <a href="https://arxiv.org/pdf/2408.16629">pdf</a>,
 <a href="https://arxiv.org/format/2408.16629">other</a>,
 <a href="https://arxiv.org/pdf/2408.16601">pdf</a>,
 <a href

In [ ]:
for i in soup.select("li.arxiv-result div span a"):
  link = i.get('href')
  if 'pdf' in link:
    print(link)

https://arxiv.org/pdf/2408.16756
https://arxiv.org/pdf/2408.16740
https://arxiv.org/pdf/2408.16737
https://arxiv.org/pdf/2408.16730
https://arxiv.org/pdf/2408.16700
https://arxiv.org/pdf/2408.16673
https://arxiv.org/pdf/2408.16667
https://arxiv.org/pdf/2408.16629
https://arxiv.org/pdf/2408.16601
https://arxiv.org/pdf/2408.16586
https://arxiv.org/pdf/2408.16542
https://arxiv.org/pdf/2408.16502
https://arxiv.org/pdf/2408.16498
https://arxiv.org/pdf/2408.16482
https://arxiv.org/pdf/2408.16465
https://arxiv.org/pdf/2408.16440
https://arxiv.org/pdf/2408.16423
https://arxiv.org/pdf/2408.16400
https://arxiv.org/pdf/2408.16345
https://arxiv.org/pdf/2408.16326
https://arxiv.org/pdf/2408.16312
https://arxiv.org/pdf/2408.16304
https://arxiv.org/pdf/2408.16296
https://arxiv.org/pdf/2408.16276
https://arxiv.org/pdf/2408.16264
https://arxiv.org/pdf/2408.16221
https://arxiv.org/pdf/2408.16219
https://arxiv.org/pdf/2408.16213
https://arxiv.org/pdf/2408.16208
https://arxiv.org/pdf/2408.16180
https://ar

In [ ]:
for i in soup.select("li.arxiv-result div span a"):
  link = i.get('href')
  if 'pdf' in link:
    print(link)
    r = requests.get(link)
    with open(f"{link.split('/')[-1]}.pdf", 'wb') as f:
      f.write(r.content)

https://arxiv.org/pdf/2408.16756
https://arxiv.org/pdf/2408.16740
https://arxiv.org/pdf/2408.16737
https://arxiv.org/pdf/2408.16730
https://arxiv.org/pdf/2408.16700
https://arxiv.org/pdf/2408.16673
https://arxiv.org/pdf/2408.16667
https://arxiv.org/pdf/2408.16629
https://arxiv.org/pdf/2408.16601
https://arxiv.org/pdf/2408.16586
https://arxiv.org/pdf/2408.16542
https://arxiv.org/pdf/2408.16502
https://arxiv.org/pdf/2408.16498
https://arxiv.org/pdf/2408.16482
https://arxiv.org/pdf/2408.16465
https://arxiv.org/pdf/2408.16440
https://arxiv.org/pdf/2408.16423
https://arxiv.org/pdf/2408.16400
https://arxiv.org/pdf/2408.16345
https://arxiv.org/pdf/2408.16326
https://arxiv.org/pdf/2408.16312
https://arxiv.org/pdf/2408.16304
https://arxiv.org/pdf/2408.16296
https://arxiv.org/pdf/2408.16276
https://arxiv.org/pdf/2408.16264
https://arxiv.org/pdf/2408.16221
https://arxiv.org/pdf/2408.16219
https://arxiv.org/pdf/2408.16213
https://arxiv.org/pdf/2408.16208
https://arxiv.org/pdf/2408.16180
https://ar

In [ ]:
link = "https://arxiv.org/pdf/2408.15915"

In [ ]:
link.split('/')[-1]

'2408.15915'

## 資料分析簡介

* numpy => 科學運算基礎套件
* matplotlib => 繪圖基礎套件
* pandas => 資料分析基礎套件

套件載入慣例
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

### NumPy (Numerical Python的縮寫)

* ndarray ==> 多維陣列 (N-Dimensional Arrays)
* ufunct ==> 通用函式 (Universal Functions)

In [1]:
import numpy as np

### list 的加法及乘法

In [2]:
x = [1, 2, 3]
y = [4, 5, 6]

In [3]:
x + y

[1, 2, 3, 4, 5, 6]

In [4]:
x * 2

[1, 2, 3, 1, 2, 3]

### ndarray

In [5]:
x1 = np.array(x)
y1 = np.array(y)

In [6]:
x1 + y1

array([5, 7, 9])

In [7]:
x1 * 2

array([2, 4, 6])

### ufunct

In [8]:
import math

In [9]:
math.pi

3.141592653589793

In [10]:
math.sin(math.pi/2)

1.0

In [12]:
math.sin(x)

TypeError: must be real number, not list

In [13]:
np.pi

3.141592653589793

In [14]:
np.sin(np.pi/2)

1.0

In [15]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])